Add Pichler LG-350 airvent modbus templates
taphome-official/modbus_templates pull request #5
Opened 2022-05-19 16:35 UTC by martindybal

2022-06-03 07:06 UTC, marian-blazicek requested changes
V modul read skripte su nejake nestandardne uvodzovky a MODBUSR funkcia potrebuje mat 3 parametre, chyba datovy typ.

2022-06-03 07:17 UTC, marian-blazicek commented
Este jedna drobnost, v novej verzii maju premenne moznost konverzie, maju potom krajsiu ikonku a mernu jednotku.
![image](https://user-images.githubusercontent.com/103591138/171806524-f6947b58-d934-40c3-8c25-8eb29de86834.png)

2022-06-08 20:05 UTC, martindybal commented
@marian-blazicek děkuji za review. 

1. V jakém read skriptu je chyba? 
1. Jakou konverzní hodnotu mám zvolit pro výkon jednotky (množství vzduchu m3/h)

2022-06-10 06:40 UTC, marian-blazicek commented
> @marian-blazicek děkuji za review.
> 
> 1. V jakém read skriptu je chyba?
- v modulovom

> 2. Jakou konverzní hodnotu mám zvolit pro výkon jednotky (množství vzduchu m3/h)
- zoznam konverzii sa postupne rozsiruje, ale takuto zatial nemame

2022-07-12 08:15 UTC, martindybal commented
@marian-blazicek upraveno.

2022-07-12 10:08 UTC, merged